/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.AppManager;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carls
 */
public class Admins extends javax.swing.JPanel {

    /**
     * Creates new form Admins
     */
    private AppManager a ;

    String userId;
    String gpId ;
    public Admins(AppManager a, String name, String photo ,String userId, String gpId) {
        initComponents();
        this.a = a;
        this.userId = userId;
        this.gpId = gpId;
        ImageIcon imageIcon = new ImageIcon(photo);
            Image image = imageIcon.getImage().getScaledInstance(
                90, 
                90, 
                Image.SCALE_SMOOTH
            );
        AdminPhoto.setIcon(new ImageIcon(image));
        AdminPhoto.setText("");
        AdminPhoto.setText(name);
        AdminName.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPhoto = new javax.swing.JLabel();
        AdminName = new javax.swing.JTextField();
        RemoveAdminButton = new javax.swing.JButton();
        DemoteButton = new javax.swing.JButton();

        AdminName.setEditable(false);

        RemoveAdminButton.setBackground(new java.awt.Color(51, 153, 255));
        RemoveAdminButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RemoveAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        RemoveAdminButton.setText("Remove");
        RemoveAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAdminButtonActionPerformed(evt);
            }
        });

        DemoteButton.setBackground(new java.awt.Color(51, 153, 255));
        DemoteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DemoteButton.setForeground(new java.awt.Color(255, 255, 255));
        DemoteButton.setText("Demote");
        DemoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(AdminPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RemoveAdminButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DemoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AdminPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(AdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveAdminButton)
                            .addComponent(DemoteButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DemoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoteButtonActionPerformed
        // TODO add your handling code here:
        a.demoteAdmin(userId, gpId);
    }//GEN-LAST:event_DemoteButtonActionPerformed

    private void RemoveAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAdminButtonActionPerformed
        // TODO add your handling code here:
        a.removeAdminFromGroup(userId, gpId);
    }//GEN-LAST:event_RemoveAdminButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminName;
    private javax.swing.JLabel AdminPhoto;
    private javax.swing.JButton DemoteButton;
    private javax.swing.JButton RemoveAdminButton;
    // End of variables declaration//GEN-END:variables
}
