/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.AppManager;
import Backend.GroupString;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carls
 */
public class GroupSuggestions extends javax.swing.JPanel {

    /**
     * Creates new form GroupSuggestions
     */
    private AppManager a;
    private String name;
    private String photo;
    private String id;
    public GroupSuggestions(AppManager a, String name, String photo, String id) {
        initComponents();
        this.a = a;
        this.name=name;
        this.photo = photo;
        this.id  =id;
        GroupName.setText(name);
        ImageIcon imageIcon = new ImageIcon(photo);
            Image image = imageIcon.getImage().getScaledInstance(
                90, 
                90, 
                Image.SCALE_SMOOTH
            );
            GroupPhoto.setIcon(new ImageIcon(image));
            GroupPhoto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupPhoto = new javax.swing.JLabel();
        GroupName = new javax.swing.JTextField();
        ViewGroupButton = new javax.swing.JButton();
        joinGroupButton1 = new javax.swing.JButton();

        GroupPhoto.setBackground(new java.awt.Color(255, 255, 255));
        GroupPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        GroupName.setEditable(false);
        GroupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupNameActionPerformed(evt);
            }
        });

        ViewGroupButton.setBackground(new java.awt.Color(0, 153, 255));
        ViewGroupButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewGroupButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewGroupButton.setText("View Group");
        ViewGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGroupButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Join Group");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);

            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GroupPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewGroupButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(joinGroupButton1)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(GroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewGroupButton)
                            .addComponent(joinGroupButton1)))
                    .addComponent(GroupPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGroupButtonActionPerformed
      new GroupForUserNotMember(a,a.getCroupInfo(id)).setVisible(true);
    }//GEN-LAST:event_ViewGroupButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         a.joinGroup(id);
    }//GEN-LAST:event_jButton1ActionPerformed

        // TODO add your handling code here:
         GroupString groupString = a.getCroupInfo(id);
         GroupForUserNotMember needJoin = new GroupForUserNotMember(a, groupString);
         needJoin.setVisible(true);

    }//GEN-LAST:event_ViewGroupButtonActionPerformed

    private void GroupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GroupNameActionPerformed

    private void joinGroupButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGroupButton1ActionPerformed
        // TODO add your handling code here:
        a.joinGroup(id);
        joinGroupButton1.setText("Pending request");
        joinGroupButton1.setEnabled(false);
    }//GEN-LAST:event_joinGroupButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GroupName;
    private javax.swing.JLabel GroupPhoto;
    private javax.swing.JButton ViewGroupButton;
    private javax.swing.JButton joinGroupButton1;
    // End of variables declaration//GEN-END:variables
}
