/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.AppManager;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carls
 */
public class NonFriendPanel extends javax.swing.JPanel {

    /**
     * Creates new form NonFriendPanel
     */
    private AppManager a;
    private String id;
    private String name;
    private String photo;
    public NonFriendPanel(String id, String name, String photo ,AppManager a) {
        initComponents();
        this.id=id;
        this.a = a;
        NameField.setText(name);
        ImageIcon imageIcon = new ImageIcon(photo);
            Image image = imageIcon.getImage().getScaledInstance(
                90, 
                90, 
                Image.SCALE_SMOOTH
            );
            PhotoLabel1.setIcon(new ImageIcon(image));
            PhotoLabel1.setText("");
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PhotoLabel1 = new javax.swing.JLabel();
        ViewProfileButton = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        AddFriendButton = new javax.swing.JButton();
        BlockButton1 = new javax.swing.JButton();

        PhotoLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewProfileButton.setBackground(new java.awt.Color(51, 153, 255));
        ViewProfileButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewProfileButton.setText("View profile");
        ViewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileButtonActionPerformed(evt);
            }
        });

        NameField.setEditable(false);

        AddFriendButton.setBackground(new java.awt.Color(51, 153, 255));
        AddFriendButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddFriendButton.setForeground(new java.awt.Color(255, 255, 255));
        AddFriendButton.setText("Add friend");
        AddFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFriendButtonActionPerformed(evt);
            }
        });

        BlockButton1.setBackground(new java.awt.Color(51, 153, 255));
        BlockButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BlockButton1.setForeground(new java.awt.Color(255, 255, 255));
        BlockButton1.setText("Block");
        BlockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PhotoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ViewProfileButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddFriendButton))
                            .addComponent(NameField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(BlockButton1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhotoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewProfileButton)
                            .addComponent(AddFriendButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlockButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileButtonActionPerformed
        new ViewProfile(a,id).setVisible(true);
    }//GEN-LAST:event_ViewProfileButtonActionPerformed

    private void AddFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFriendButtonActionPerformed
        a.sendFriendRequest(id);
    }//GEN-LAST:event_AddFriendButtonActionPerformed

    private void BlockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockButton1ActionPerformed
       a.blockNonFriend(id);
    }//GEN-LAST:event_BlockButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFriendButton;
    private javax.swing.JButton BlockButton1;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel PhotoLabel1;
    private javax.swing.JButton ViewProfileButton;
    // End of variables declaration//GEN-END:variables
}
