/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.AppManager;
import Backend.Friend_Management.UserSearch;
import Frontend.Search.BlockedSearch;
import Frontend.Search.FriendListSearch;
import Frontend.Search.FriendRequestSearch;
import Frontend.Search.FriendSuggestionSearch;
import java.util.ArrayList;

/**
 *
 * @author carls
 */
public class SearchResult extends javax.swing.JFrame {
    private AppManager a;
    private ArrayList<UserSearch> found;
    public SearchResult(AppManager a,ArrayList<UserSearch> found) {
        this.a=a;
        this.found=found;
        initComponents();
        friendSearch.setLayout(new javax.swing.BoxLayout(friendSearch, javax.swing.BoxLayout.Y_AXIS));
        this.found = found;

        friendSearch.removeAll();
        for (int i = 0; i < found.size(); i++) {
            String id = found.get(i).getIdString();
            String photo = found.get(i).getRelationString();
            String name = found.get(i).getUsernameString();
            switch (found.get(i).getRelationString()) {
                case "Friend":
                    friendSearch.add(new FriendsPanel(id, name, photo, a));
                    break;
                case "No Relation":
                    friendSearch.add(new NonFriendPanel(id, name, photo, a));
                    break;
                case "Blocked":
                    friendSearch.add(new BlockedSearch(id, name, photo, a));
                    break;
                case"Pending":
                    friendSearch.add(new FriendRequestSearch(id, name, photo, a));
                    break;
            }
        }
        friendSearch.revalidate();
        friendSearch.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchResultPane = new javax.swing.JScrollPane();
        friendSearch = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout friendSearchLayout = new javax.swing.GroupLayout(friendSearch);
        friendSearch.setLayout(friendSearchLayout);
        friendSearchLayout.setHorizontalGroup(
            friendSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        friendSearchLayout.setVerticalGroup(
            friendSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        SearchResultPane.setViewportView(friendSearch);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(SearchResultPane, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(SearchResultPane, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SearchResultPane;
    private javax.swing.JPanel friendSearch;
    // End of variables declaration//GEN-END:variables
}
